#!/bin/sh
# SetSwedishKeyboard
if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
ChmodCMD="$TARGETVOL/bin/chmod" && \
ChownCMD="$TARGETVOL/usr/sbin/chown" && \
DefaultsCMD="$TARGETVOL/usr/bin/defaults" && \
RmCMD="$TARGETVOL/bin/rm" && \
TouchCMD="$TARGETVOL/usr/bin/touch" && \
CURRENT_FILE="$TARGETVOL/Library/Preferences/com.apple.HIToolbox.plist" && \
"$RmCMD" -f "$CURRENT_FILE" && \
"$TouchCMD" "$CURRENT_FILE" && \
"$DefaultsCMD" write "$CURRENT_FILE" AppleCurrentKeyboardLayoutInputSourceID com.apple.keylayout.Swedish-Pro && \
"$DefaultsCMD" write "$CURRENT_FILE" AppleDateResID -dict smRoman -int 7 && \
"$DefaultsCMD" write "$CURRENT_FILE" AppleNumberResID -dict smRoman -int 7 && \
"$DefaultsCMD" write "$CURRENT_FILE" AppleTimeResID -dict smRoman -int 7 && \
"$DefaultsCMD" write "$CURRENT_FILE" AppleDefaultAsciiInputSource -dict "InputSourceKind" "Keyboard Layout" "KeyboardLayout ID" -int "7" "KeyboardLayout Name" "Swedish - Pro" && \
"$DefaultsCMD" write "$CURRENT_FILE" "AppleEnabledInputSources" -array-add '<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>7</integer><key>KeyboardLayout Name</key><string>Swedish - Pro</string></dict>' && \
"$DefaultsCMD" write "$CURRENT_FILE" "AppleInputSourceHistory" -array-add '<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>7</integer><key>KeyboardLayout Name</key><string>Swedish - Pro</string></dict>' && \
"$DefaultsCMD" write "$CURRENT_FILE" "AppleSelectedInputSources" -array-add '<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>7</integer><key>KeyboardLayout Name</key><string>Swedish - Pro</string></dict>' && \
"$ChmodCMD" 644 "$CURRENT_FILE" && \
"$ChownCMD" root:wheel "$CURRENT_FILE" && \
exit 0