#!/bin/sh
# SetSwedishKeyboard

if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
#TARGETVOL="{{target_volume}}"

KeyboardLayoutName="Swedish - Pro"
KeyboardLayout="Swedish-Pro"
KeyboardLayoutID="7"


PLBUDDY="$TARGETVOL/usr/libexec/PlistBuddy"

update_kdb_layout() {
  #logger "SetSwedishKeyboard Updating file '${1}'"
  echo "SetSwedishKeyboard Updating file '${1}'" >> "$TARGETVOL"/log.txt
  ${PLBUDDY} -c "Delete :AppleCurrentKeyboardLayoutInputSourceID" "${1}" &>/dev/null
  if [ ${?} -eq 0 ] || [ -n "${4}" ]
  then
    #${PLBUDDY} -c "Add :AppleCurrentKeyboardLayoutInputSourceID string com.apple.keylayout.${2}" "${1}"
    ${PLBUDDY} -c "Add :AppleCurrentKeyboardLayoutInputSourceID string com.apple.keylayout.$KeyboardLayout" "${1}"
  fi

  for SOURCE in AppleDefaultAsciiInputSource AppleCurrentAsciiInputSource AppleCurrentInputSource AppleEnabledInputSources AppleSelectedInputSources
  do
    ${PLBUDDY} -c "Delete :${SOURCE}" "${1}" &>/dev/null
    if [ ${?} -eq 0 ] || [ -n "${4}" ]
    then
      ${PLBUDDY} -c "Add :${SOURCE} array" "${1}"
      ${PLBUDDY} -c "Add :${SOURCE}:0 dict" "${1}"
      ${PLBUDDY} -c "Add :${SOURCE}:0:InputSourceKind string 'Keyboard Layout'" "${1}"
      ${PLBUDDY} -c "Add :${SOURCE}:0:KeyboardLayout\ ID integer ${3}" "${1}"
      ${PLBUDDY} -c "Add :${SOURCE}:0:KeyboardLayout\ Name string '${2}'" "${1}"
    fi
  done
}

touch "$TARGETVOL/Library/Preferences/com.apple.HIToolbox.plist"
chmod 644 "$TARGETVOL/Library/Preferences/com.apple.HIToolbox.plist"
chown root:wheel "$TARGETVOL/Library/Preferences/com.apple.HIToolbox.plist"
update_kdb_layout "$TARGETVOL/Library/Preferences/com.apple.HIToolbox.plist" "$KeyboardLayoutName" "$KeyboardLayoutID" --force


exit 0