#!/bin/sh
# SetStockholmTimeZone

if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
ChmodCMD="$TARGETVOL/bin/chmod" && \
ChownCMD="$TARGETVOL/usr/sbin/chown" && \
LnCMD="$TARGETVOL/bin/ln" && \
RmCMD="$TARGETVOL/bin/rm" && \
CURRENT_FILE="$TARGETVOL/private/etc/localtime" && \
"$RmCMD" -f "$CURRENT_FILE" && \
"$LnCMD" -s "/usr/share/zoneinfo/Europe/Stockholm" "$CURRENT_FILE" && \
"$ChmodCMD" 755 "$CURRENT_FILE" && \
"$ChownCMD" root:wheel "$CURRENT_FILE" && \
exit 0