#!/bin/sh
# Setmunkihag

if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
#TARGETVOL="{{target_volume}}"

DefaultsCMD="$TARGETVOL/usr/bin/defaults"
file="$TARGETVOL/private/var/root/Library/Preferences/ManagedInstalls.plist"

touch "$file"
# -rw-r--r--
chmod 644 "$file"
chown root:wheel "$file"
"$DefaultsCMD" write "$file" SoftwareRepoURL 'http://munkihag.admbs.mbs08.se/repo'



