#!/bin/sh
# SetSwedishRegion

if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
#TARGETVOL="{{target_volume}}"

DefaultsCMD="$TARGETVOL/usr/bin/defaults"
file="$TARGETVOL/Library/Preferences/.GlobalPreferences.plist"

touch "$file" 
"$DefaultsCMD" write "$file" AppleLocale sv_SE
"$DefaultsCMD" write "$file" Country SE