#!/bin/sh
# SetSwedishRegion

if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
#TARGETVOL="{{target_volume}}"

DefaultsCMD="$TARGETVOL/usr/bin/defaults" && \
    logger "SetSwedishRegion : DefaultsCMD=$DefaultsCMD"

file="$TARGETVOL/Library/Preferences/.GlobalPreferences.plist" && \
    logger "SetSwedishRegion : file=$file"

touch "$file" && \
    logger "SetSwedishRegion : touch $file"

"$DefaultsCMD" write "$file" AppleLocale sv_SE && \
    logger "SetSwedishRegion : $DefaultsCMD write $file AppleLocale sv_SE"

"$DefaultsCMD" write "$file" Country SE && \
    logger "SetSwedishRegion : $DefaultsCMD write $file Country SE"