#!/bin/sh
# SetSwedishRegion

if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
ChmodCMD="$TARGETVOL/bin/chmod" && \
ChownCMD="$TARGETVOL/usr/sbin/chown" && \
DefaultsCMD="$TARGETVOL/usr/bin/defaults" && \
TouchCMD="$TARGETVOL/usr/bin/touch" && \
CURRENT_FILE="$TARGETVOL/Library/Preferences/.GlobalPreferences.plist" && \
"$TouchCMD" "$CURRENT_FILE" && \
"$DefaultsCMD" write "$CURRENT_FILE" AppleLocale sv_SE && \
"$DefaultsCMD" write "$CURRENT_FILE" Country SE && \
"$ChmodCMD" 644 "$CURRENT_FILE" && \
"$ChownCMD" root:wheel "$CURRENT_FILE" && \
exit 0