#!/bin/sh
# DisableIcloudOnLogin
# Determine the volume to install to
if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
AwkCMD="$TARGETVOL/usr/bin/awk" && \
ChmodCMD="$TARGETVOL/bin/chmod" && \
ChownCMD="$TARGETVOL/usr/sbin/chown" && \
DefaultsCMD="$TARGETVOL/usr/bin/defaults" && \
EchoCMD="$TARGETVOL/bin/echo" && \
MkdirCMD="$TARGETVOL/bin/mkdir" && \
PRODUCT_VERSION="$("$DefaultsCMD" read "$TARGETVOL/System/Library/CoreServices/SystemVersion.plist" ProductVersion)" && \
MAIN_PRODUCT_VERSION=$("$DefaultsCMD" read "$TARGETVOL/System/Library/CoreServices/SystemVersion.plist" ProductVersion | "$AwkCMD" -F. '{print $2}')
PRODUCT_BUILD_VERSION="$("$DefaultsCMD" read "$TARGETVOL/System/Library/CoreServices/SystemVersion.plist" ProductBuildVersion)" && \
if [[ ${MAIN_PRODUCT_VERSION} -ge 7 ]] ; then
    for USER_TEMPLATE in "$TARGETVOL/System/Library/User Template"/* ; do
        "$DefaultsCMD" write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE && \
        "$DefaultsCMD" write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none && \
        "$DefaultsCMD" write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion "${PRODUCT_VERSION}" && \
        "$DefaultsCMD" write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant LastSeenBuddyBuildVersion "${PRODUCT_BUILD_VERSION}" 
    done
    for USER_HOME in "$TARGETVOL"/Users/* ; do
    USER_UID="$(basename "${USER_HOME}")"
        if [ ! "${USER_UID}" = "Shared" ]; then
            if [ ! -d "${USER_HOME}"/Library/Preferences ] ; then
                "$MkdirCMD" -p "${USER_HOME}"/Library/Preferences && \
                "$ChownCMD" "${USER_UID}" "${USER_HOME}"/Library && \
                "$ChownCMD" "${USER_UID}" "${USER_HOME}"/Library/Preferences && \
            fi
            if [ -d "${USER_HOME}"/Library/Preferences ] ; then
                "$DefaultsCMD" write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE && \
                "$DefaultsCMD" write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none && \
                "$DefaultsCMD" write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion "${PRODUCT_VERSION}" && \
                "$DefaultsCMD" write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant LastSeenBuddyBuildVersion "${PRODUCT_BUILD_VERSION}" && \
                "$ChownCMD" "${USER_UID}" "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant.plist
            fi
        fi
    done
fi
exit 0