#!/bin/sh
# DisableErrorReporting

if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
#TARGETVOL="{{target_volume}}"
DefaultsCMD="$TARGETVOL/usr/bin/defaults"

# Determine OS version
ProductVersion="$("$DefaultsCMD" read "$TARGETVOL/System/Library/CoreServices/SystemVersion.plist" ProductVersion)"

# Determine Main OS version
MainProductVersion=$(echo "$ProductVersion" | awk -F. '{print $2}')

# Determine OS build number
ProductBuildVersion="$("$DefaultsCMD" read "$TARGETVOL/System/Library/CoreServices/SystemVersion.plist" ProductBuildVersion)"


# Checks first to see if the Mac is running 10.7.0 or higher. 
# If so, the script checks the system default user template
# for the presence of the Library/Preferences directory. Once
# found, the iCloud and Diagnostic pop-up settings are set 
# to be disabled.

if [[ ${MainProductVersion} -ge 7 ]]; then
#echo "DisableErrorReporting : MainProductVersion -ge 7" >> "$TARGETVOL"/log.txt
 for USER_TEMPLATE in "$TARGETVOL/System/Library/User Template"/*
  do
    "$DefaultsCMD" write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE
    "$DefaultsCMD" write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
    "$DefaultsCMD" write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion "${ProductVersion}"
    "$DefaultsCMD" write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant LastSeenBuddyBuildVersion "${ProductBuildVersion}"      
  done

# Checks first to see if the Mac is running 10.7.0 or higher.
 # If so, the script checks the existing user folders in /Users
 # for the presence of the Library/Preferences directory.
 #
 # If the directory is not found, it is created and then the
 # iCloud and Diagnostic pop-up settings are set to be disabled.

 for USER_HOME in "$TARGETVOL"/Users/*
  do
  	#echo "DisableErrorReporting : USER_HOME=$USER_HOME" >> "$TARGETVOL"/log.txt
    USER_UID="$(basename "${USER_HOME}")"
    #echo "DisableErrorReporting : USER_UID=$USER_UID" >> "$TARGETVOL"/log.txt
    if [ ! "${USER_UID}" = "Shared" ]; then
      if [ ! -d "${USER_HOME}"/Library/Preferences ]; then
        "$TARGETVOL"/bin/mkdir -p "${USER_HOME}"/Library/Preferences
        "$TARGETVOL"/usr/sbin/chown "${USER_UID}" "${USER_HOME}"/Library
        "$TARGETVOL"/usr/sbin/chown "${USER_UID}" "${USER_HOME}"/Library/Preferences
      fi
      if [ -d "${USER_HOME}"/Library/Preferences ]; then
        "$DefaultsCMD" write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE
        "$DefaultsCMD" write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
        "$DefaultsCMD" write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion "${ProductVersion}"
        "$DefaultsCMD" write "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant LastSeenBuddyBuildVersion "${ProductBuildVersion}"
        "$TARGETVOL"/usr/sbin/chown "${USER_UID}" "${USER_HOME}"/Library/Preferences/com.apple.SetupAssistant.plist
      fi
    fi
  done
fi

exit 0

