#!/bin/sh
# DisableErrorReporting
SUBMIT_DIAGNOSTIC_DATA_TO_APPLE=FALSE
SUBMIT_DIAGNOSTIC_DATA_TO_APP_DEVELOPERS=FALSE
# Determine the volume to install to
if [ "$3" == "/" ]; then
    TARGETVOL=""
else
    TARGETVOL="$3"
fi
AwkCMD="$TARGETVOL/usr/bin/awk" && \
ChmodCMD="$TARGETVOL/bin/chmod" && \
ChownCMD="$TARGETVOL/usr/sbin/chown" && \
DefaultsCMD="$TARGETVOL/usr/bin/defaults" && \
MAIN_PRODUCT_VERSION=$("$DefaultsCMD" read "$TARGETVOL/System/Library/CoreServices/SystemVersion.plist" ProductVersion | "$AwkCMD" -F. '{print $2}')
if [[ ${MAIN_PRODUCT_VERSION} -ge 10 ]] ; then
    CRASHREPORTER_SUPPORT="$TARGETVOL/Library/Application Support/CrashReporter"
    if [ ! -d "${CRASHREPORTER_SUPPORT}" ] ; then
        mkdir "${CRASHREPORTER_SUPPORT}" && \
        chmod 775 "${CRASHREPORTER_SUPPORT}" && \
        chown root:admin "${CRASHREPORTER_SUPPORT}" && \
    fi
    "$DefaultsCMD" write "$CRASHREPORTER_SUPPORT"/DiagnosticMessagesHistory AutoSubmit -boolean ${SUBMIT_DIAGNOSTIC_DATA_TO_APPLE} && \
    "$DefaultsCMD" write "$CRASHREPORTER_SUPPORT"/DiagnosticMessagesHistory AutoSubmitVersion -int 4 && \
    "$DefaultsCMD" write "$CRASHREPORTER_SUPPORT"/DiagnosticMessagesHistory ThirdPartyDataSubmit -boolean ${SUBMIT_DIAGNOSTIC_DATA_TO_APP_DEVELOPERS} && \
    "$DefaultsCMD" write "$CRASHREPORTER_SUPPORT"/DiagnosticMessagesHistory ThirdPartyDataSubmitVersion -int 4 && \
    "$ChmodCMD" a+r "$CRASHREPORTER_SUPPORT"/DiagnosticMessagesHistory.plist && \
    "$ChownCMD" root:admin "$CRASHREPORTER_SUPPORT"/DiagnosticMessagesHistory.plist
fi
exit 0